export const CHANGE_GOODS_LIST = 'CHANGE_GOODS_LIST'
export const GET_LOADING = 'GET_LOADING'
export const CHNAGE_GOODS_NUM = 'CHNAGE_GOODS_NUM'
export const CHNAGE_GOODSAll_NUM = 'CHNAGE_GOODSAll_NUM'